### ISSUE TITLE
=== null

### ISSUE THREAD

**Issue by thepian** [felixge/node-style-guide#33]
I have no issue with the advice of using === by default, but it really is silly to tell people to write

if (result === undefined || result===null) {

when you can do

if (result==null) {

In most cases you want to catch both.

**Comment by thepian** [comment]
Except for the 90% of people that adopt rules as religion rather than general advice. 

There are cases where if (!result) will catch too much, but it is very rare(I haven't seen it in 8 years) that (result == null) will catch a case you didn't want to handle.

**Comment by stevenvachon** [comment]
`if (!result)` is incorrect. We do not want to catch `0` and `""`.

**Comment by arthurhamon** [comment]
In this case use if(typeof results !== 'undefined')

**Comment by stevenvachon** [comment]
strings are slower

**Comment by stevenvachon** [comment]
also, `typeof null === "object"`

**Comment by thepian** [comment]
`typeof results === 'undefined'` is unfortunately ingrained in JS developers. It is a special case for handling the results variable not being defined at all. For modern JS developers that should never(almost) be the case. Linting should catch this case.

`results !== undefined` - Any sort of value is ok including null
`results != null` - Any sort of value is ok excluding null

I would use `if (!result)` as well, but many developers are milk fed on strict typing ideologies, and I don't wan't to waste my life with `goto` discussions.

**Comment by stevenvachon** [comment]
Linting your application is one thing, linting dependencies is another. It's possible for a third-party module to return `undefined` instead of `null`, even if it's documentation specifies otherwise.
