### ISSUE TITLE
.jscsrc

### ISSUE THREAD

**Issue by matmuchrapna** [felixge/node-style-guide#54]
Hey, what about .jscsrc config to add here?

**Comment by hzoo** [comment]
I'm actually starting work on that now! https://github.com/jscs-dev/node-jscs/pull/1091

**Comment by hzoo** [comment]
Ok it's a preset now from https://github.com/jscs-dev/node-jscs/pull/1091

```js
{
  "preset": "node-style-guide"
}
```

**Comment by matmuchrapna** [comment]
Thanks!
