### ISSUE TITLE
Allow docblocks

### ISSUE THREAD

**Issue by callumacrae** [felixge/node-style-guide#56]
I'm a big fan of docblocks, and it's the only place I will use a multi-line comment:

```js
/**
 * Function description here.
 *
 * @param {string} test Some argument.
 */
function doSomething(test) {}
```

It works great with IDEs—mine will give me a warning if the arguments don't match up to the comment, and then when I use the function will validate the input to make sure it's the correct type, which also helps keep the docs up to date.

There are tools such as [JSDoc] which will parse these to generate documentation for you.

This syntax is currently disallowed in node-style-guide, and I find it pretty useful. Would you accept a PR that adds something like the following?

> The only case a multi-line comment is allowed is as a [docblock][JSDoc] immediately before a function:
>
> ```js
>// The code block from above
>```

[JSDoc]: http://usejsdoc.org/about-getting-started.html

**Comment by kentcdodds** [comment]
:+1:

**Comment by felixge** [comment]
I'm not against docblocks, but I prefer the informal Go way of documenting methods (i.e. no special syntax for describing individual arguments). This guide is meant to be forked and adjusted to your liking, so you should totally go ahead and do that. At this point the only major changes I'd consider would be related to adjusting the guide for ES6.

**Comment by callumacrae** [comment]
> the informal Go way of documenting methods (i.e. no special syntax for describing individual arguments)

Could you expand on this? I'd rather not fork anything, because I don't want to force people to read an entire styleguide to see what has changed—and if the Go approach works, it could be interesting. Also, if JSCS are adding node-style-guide as a preset, I don't want to have to fork JSCS to change this: jscs-dev/node-jscs#1071

It be something as simple as saying "The only place multi-line comments are allowed are in DocBlocks"? Short enough that people who are no familiar with DocBlocks will read past it, long enough that people who care about DocBlocks will be happy.

**Comment by felixge** [comment]
More about the Go way of documenting: http://blog.golang.org/godoc-documenting-go-code

Do docblock comments not work with slashes?

**Comment by callumacrae** [comment]
Don't think so: they're specifically marked as DocBlocks by the syntax of using two asterisks at the beginning and beginning each line with an asterisk.

I've taken a few screenshots of why I'm a huge fan of DocBlocks. The Go approach of documenting just can't do this.

![screen shot 2015-02-23 at 12 46 25](https://cloud.githubusercontent.com/assets/472830/6327976/0dce5cda-bb5a-11e4-8793-fc5180439dcd.png)
![screen shot 2015-02-23 at 12 45 47](https://cloud.githubusercontent.com/assets/472830/6327978/0dd042e8-bb5a-11e4-997c-8e06557e8f26.png)
![screen shot 2015-02-23 at 12 45 58](https://cloud.githubusercontent.com/assets/472830/6327977/0dcf908c-bb5a-11e4-9adf-c0e300a09e34.png)
![screen shot 2015-02-23 at 12 46 13](https://cloud.githubusercontent.com/assets/472830/6327979/0dd3a226-bb5a-11e4-8d98-a598cd7c5f0f.png)
