### ISSUE TITLE
Why declare multiple var is right in node.js but wrong in javascript

### ISSUE THREAD

**Issue by lovedota** [felixge/node-style-guide#61]
https://github.com/felixge/node-style-guide#declare-one-variable-per-var-statement

Thanks !

**Comment by beautifulcoder** [comment]
I also wondered about that, JavaScript is function scoped. Is there something else going on in Node.js?

**Comment by felixge** [comment]
The recommendation is purely stylistic. I'd recommend the same for non-node JS.
