### ISSUE TITLE
Why 2 space indentation

### ISSUE THREAD

**Issue by Phoenix1708** [felixge/node-style-guide#62]
2 space indentation doesn't actually looks good when the name of variables and method/functions getting longer, since it won't align the body of, say if statement, to the if condition which also happens to function signature and function body etc . Check the following

2 space:
```
      if (checkPointer !== undefined && checkPointer !== null) {
        checkPointer.checkpoint(blah_blah, function (err) {
          if (!err) {
            log.info('blah_blah.................................');
          }
          checkpointComplete(err);
        });
      } else {
        log.info("blah_blah..............................");
        checkpointComplete();
      }
```

4 space:
```
            if (checkPointer !== undefined && checkPointer !== null) {
                checkPointer.checkpoint(blah_blah, function (err) {
                    if (!err) {
                        log.info('blah_blah..........................');
                    }
                    checkpointComplete(err);
                });
            } else {
                log.info("blah_blah....................................");
                checkpointComplete();
            }
```

**Comment by felixge** [comment]
To quote the README:

> It is inspired by what is popular within the community, and flavored with some personal opinions.

and

> You are encouraged to fork this repository and make adjustments according to your preferences.

**Comment by MichaelPaulukonis** [comment]
How often do you want/need to align the body to the condition?

After 13 years of getting paid for this, this has never once been a consideration for me.

I had to read your comment several times before I could even see what your issue is.

If it is burningly, painfully obvious for you -- don't indent 2 spaces in your code, hooray!

**Comment by iorlas** [comment]
There is a reason to use 2 spaces in JS - because of many nested blocks(like callbacks). It is easier to read JS code with 2 spaces.

**Comment by Phoenix1708** [comment]
OK guys, thanks for your comments and take it easy :)

I only want to raise some points and get some ideas and comments etc. and to be honest this really is not some big issue. 

@felixge I am just suggesting something as someone from the community and I am not saying that we all have to do things in certain way etc. Finally, the reason I raise this is because that I don't have the freedom to make adjustments due to this style guide :

The team that I am currently working with requires everyone to follows this guide. We have a "significant" focus on coding style and readability etc. (even all the "=" signs have to be on the same column for declaring variables etc, which is fine to me) but I personally doesn't feel 2 spaces helps with readability. i.e I feel that align statement body with condition is neater (maybe not necessary 4 spaces). Once different parts of the code aligned (as my example above) it gives us an implicit visual structure / pattern, which helps us easily identify things. Humans are quite good at identifying and following patterns I believe.

@iorlas yes, the callback hell, or nested block hell if you like, is indeed a problem for JavaScript and people has been using various libraries to get rid of it, but I don't see how "less separation (spaces)" helps with identifying nested (i.e different) component of the code.

Finally, I am using the WebStorm IDE which has 4 spaces indention by default for JavaScript and also I believe Python is a language which has a great focus on coding style and 4 spaces is recommended by Python. Perhaps this standard from another scripting language means something. :) Again, happy commenting and take it easy.

**Comment by felixge** [comment]
@Phoenix1708 sorry for my short reply, but most of the node community uses 2 spaces for indention (or at least this was true when I created this guide, I'm not longer part of the node community), and I personally prefer it as well, so I won't change it in my version of the guide.

This last point is important: This guide is not meant to be taken as-is. You are encouraged to fork the repository and make changes according to the preferences of your team. If your team prefers 2 spaces, you'll have to convince them, not me.

**Comment by Phoenix1708** [comment]
Thanks @felixge. Not trying to convince you, neither making changes to this guide but just want to ask a question, as the title of this issue says and most people using 2 spaces isn't convincing to be honest. Most people just blindly following things as long as it's not a big issue. Anyway, shut up now :)

Again, thanks to all taking time to read and reply on this !
