### ISSUE TITLE
The .jshintrc doesn't meet your standrads

### ISSUE THREAD

**Issue by frederickbrock** [felixge/node-style-guide#68]
Strings should use single  qoute...the jshintrc has double. 

   "camelcase": true,
                          ^ Strings must use singlequote.
     10 |        "curly": true,
                        ^ Strings must use singlequote.
     11 |        "eqeqeq": true,
                         ^ Strings must use singlequote.
     12 |        "freeze": true,
                         ^ Strings must use singlequote.
     13 |        "indent": 2,
                         ^ Strings must use singlequote.
     14 |        "newcap": true,
                         ^ Strings must use singlequote.
     15 |        "quotmark": "single",
                           ^ Strings must use singlequote.
     15 |        "quotmark": "single",
                                     ^ Strings must use singlequote.
     16 |        "maxdepth": 3,
                           ^ Strings must use singlequote.
     17 |        "maxstatements": 15,
                                ^ Strings must use singlequote.
     18 |        "maxlen": 80,
                         ^ Strings must use singlequote.
     19 |        "eqnull": true,
                         ^ Strings must use singlequote.
     20 |        "funcscope": true,
                            ^ Strings must use singlequote.
     21 |        "node": true

**Comment by kentcdodds** [comment]
The `.jshintrc` is actually not JavaScript, but JSON and AFAIK, JSON doesn't allow for double quoted keys. Either way, this file doesn't need to be linted...

**Comment by frederickbrock** [comment]
Your right. My bad. I actually copied the jshintrc file into  my grunt configuration and that is when I got the error.
