### ISSUE TITLE
Push to npm

### ISSUE THREAD

**Issue by callumacrae** [felixge/node-style-guide#69]
Hey, would you be able to push this project to npm? It would be super useful for extending ESLint config from.

Thanks!

**Comment by pdehaan** [comment]
@callumacrae I published it separately as https://www.npmjs.com/package/eslint-config-node-style-guide, if that helps.

**Comment by callumacrae** [comment]
I know, but it would be nice to have the actual author push it to keep it up to date! I made that mistake with jquery-ujs, ended up having to maintain it long after I finished using it.

**Comment by kentcdodds** [comment]
Meh, that same thing can happen even for the library author ;-)

**Comment by felixge** [comment]
I'm sorry, but I'm not interested in maintain any more npm modules, since moving to Golang I'm already doing a terrible job with all the other modules I published in the past.

That being said, if anybody wants to handle it, just go for it.

**Comment by callumacrae** [comment]
@felixge Would you be willing to accept a PR adding a package.json so someone else can push it without having to fork it?

**Comment by felixge** [comment]
@callumacrae yes, definitely

**Comment by pdehaan** [comment]
package.json file added in PR #72
