### ISSUE TITLE
statement inside curly braces should be on next line(arrow functions)

### ISSUE THREAD

**Issue by nixoncode** [felixge/node-style-guide#97]
.i have this line
```js
app.listen(PORT, () => { console.log(`app running on http://localhost:${PORT}`)});
```
basically i want it to be a single line while i keep the rule for other normal function.
here is. how it errors in vs code 
![eslint rc](https://user-images.githubusercontent.com/15726312/32695483-c7f5a104-c76e-11e7-9815-795f56ba16b3.png)

**Comment by ivanoff** [comment]
Can you write this line without curly braces?
app.listen(PORT, () => console.log(`app running on http://localhost:${PORT}`) );

**Comment by nixoncode** [comment]
sweet
